# Generated by Django 5.2.4 on 2026-07-09 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_current_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('artwork', models.URLField(blank=True)),
                ('preview_url', models.URLField()),
                ('votes', models.IntegerField(default=0)),
                ('played', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue', to='api.room')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100)),
                ('queue_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.queueitem')),
            ],
            options={
                'unique_together': {('queue_item', 'session_key')},
            },
        ),
    ]
